### ISSUE TITLE
Using pretrained model fern_2v,render only,but CUDA out of memory

### ISSUE THREAD

**Issue by Seagullflysxt** [dunbar12138/DSNeRF#50]
`Traceback (most recent call last):
  File "D:\graduate\nerf\DSNeRF-main\run_nerf.py", line 1134, in <module>
    train()
  File "D:\graduate\nerf\DSNeRF-main\run_nerf.py", line 795, in train
    rgbs, disps = render_path(render_poses, hwf, args.chunk, render_kwargs_test, gt_imgs=images, savedir=testsavedir, render_factor=args.render_factor)
  File "D:\graduate\nerf\DSNeRF-main\run_nerf.py", line 168, in render_path
    rgb, disp, acc, depth, extras = render(H, W, focal, chunk=chunk, c2w=c2w[:3,:4], retraw=True, **render_kwargs)
  File "D:\graduate\nerf\DSNeRF-main\run_nerf.py", line 140, in render
    all_ret = batchify_rays(rays, chunk, **kwargs)
  File "D:\graduate\nerf\DSNeRF-main\run_nerf.py", line 71, in batchify_rays
    ret = render_rays(rays_flat[i:i+chunk], **kwargs)
  File "D:\graduate\nerf\DSNeRF-main\run_nerf.py", line 449, in render_rays
    raw = network_query_fn(pts, viewdirs, run_fn)
  File "D:\graduate\nerf\DSNeRF-main\run_nerf.py", line 273, in <lambda>
    network_query_fn = lambda inputs, viewdirs, network_fn : run_network(inputs, viewdirs, network_fn,
  File "D:\graduate\nerf\DSNeRF-main\run_nerf.py", line 59, in run_network
    embedded = torch.cat([embedded, embedded_dirs], -1)
RuntimeError: CUDA out of memory. Tried to allocate 2.11 GiB (GPU 0; 12.00 GiB total capacity; 6.76 GiB already allocated; 0 bytes free; 9.79 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

Than I reduce the batch size(N_rand) from 4096 to 2, but no progress yet.

**Comment by dunbar12138** [comment]
Thanks for your interest!

Honestly I didn't test my code on windows. But it seems you are allocating RAM instead of GPU Memory. Could you make sure you're using CUDA?

Also, do you have the full error log? That might also help.

**Comment by Seagullflysxt** [comment]
> 

Thanks for your reply!

I changed another device with higher cuda memory(24G),the problem above is solved.
But I encounterd another problem:
When I came to 4999 iters, a type error happend:
TypeError: expected TensorOptions(dtype=float, device=cpu, layout=Strided, requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt)) (got TensorOptions(dtype=float, device=cuda:0, layout=Strided, requires_grad=false (default)

Using RTX 3090(24G), on Linux, pytorch 1.10.0, cuda 11.3

**Comment by dunbar12138** [comment]
I cannot reproduce this error on my end. Could you make sure you have pulled the latest version?

**Comment by yyzzyy78** [comment]
Thanks for your work!
I meet the same error with the latest version of the project, with cuda11.1 and pytorch1.7.0.

**Comment by yyzzyy78** [comment]
Thanks for your work!
I solved the issue by changing the item torch.Tensor(poses[i_test]).to(device) to 
poses[i_test]
